version: '3.7'

services:
  server:
    image: sarasmiseth/prosody:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5222:5222"
      - "5223:5223"
      - "5269:5269"
      - "5281:5281"
    environment:
      DOMAIN: chat.a-nord.se
      DOMAIN_MUC: muc.a-nord.se
      DOMAIN_PROXY: proxy.a-nord.se
      DOMAIN_HTTP_UPLOAD: null
      DOMAIN_PUBSUB: null
      PROSODY_ADMINS: "admin@chat.a-nord.se, admin2@chat.a-nord.se"
    volumes:
      - ./certs:/usr/local/etc/prosody/certs
